### PR TITLE
Update themes.yml

### PR DESCRIPTION
**Pull request by ramswaroop**
Added new theme

### CODE REVIEW

**Comment by geraldb** [comment]
@ramswaroop  Thanks for adding Photography. Note: You're missing the preview screenshoot pic 250x200 px. Please add if you want to add your theme.  Cheers.

**Comment by geraldb** [comment]
@ramswaroop  Are you still interested in adding your theme?

**Comment by ramswaroop** [comment]
Yes, would be adding the thumbnail in a while.

**Comment by geraldb** [comment]
@ramswaroop I added the missing screenshoot 250x200 px. Cheers.

**Pull request merged**
