### PR TITLE
update Urban theme

### PR DESCRIPTION
**Pull request by midzer**
Hi,
i want to have my theme updated.

Thanks and have a nice week!

### CODE REVIEW

**Comment by geraldb** [comment]
Thanks for the theme update - I try to push out an update later this year. Cheers.

**Comment by midzer** [comment]
@geraldb Sorry for my message and I don't want to push you. Do you have an approx. ETA of when there will be a site update?

**Comment by geraldb** [comment]
Sorry for the bad news -   the plan is to  close down planet jekyll and dr. jekyll - the good news is that I have to find time :-) - so the sites will be up for some more month (and I might change my mind if my current personal / financial situation gets better - maybe next year).

**Comment by midzer** [comment]
Oh, why close it down? Do you need help for hosting?

**Comment by geraldb** [comment]
> Oh, why close it down?

There's nobody here (after all these years) only myself and I am in a crisis and can't find the the time (the good news - even for closing down).  As said above maybe things look different in a year.

**Comment by midzer** [comment]
Any news on this?

**Comment by geraldb** [comment]
Sorry - same old.

**Comment by midzer** [comment]
Hi @geraldb 
I hope you're doing good. If you need any assistance for the site update, just message me.

Have a nice week
midzer

**Comment by geraldb** [comment]
sorry this site is shutting down - the good news I have no time now (so it will live on as a "zombie" for now)

@midzer  

>  If you need any assistance for the site update, just message me

If that means more than questions about your theme / update , that is, that YOU are interested in updating the website - you are welcome - I can transfer the org to you, for example.

**Comment by midzer** [comment]
Several months ago I started by cloning of the repos and tried to build it. But apparently my jekyll version was too new (v4), so it failed.

I have no idea where to start to be honest...

**Comment by geraldb** [comment]
Thanks for trying.  Sorry for now  I can offer no more support. Same old. See above.

**Comment by midzer** [comment]
Finally, I've managed to get the whole site updated: https://drjekyll.netlify.app/

What next?

**Comment by geraldb** [comment]
@midzer   wow. thanks for your efforts.
> What next?
looking at your github profile i trust you.  that is - i can offer you two options:
1) i add you as owner on drjekllthemes and you can do whatever
2) i add you as member with full-write access to all repos 

whatever you prefer - you tell me. or what are you thinking?
you are welcome to update or upgrade the website.

**Comment by midzer** [comment]
Thing is,

I wonder how to update GitHub Pages for https://github.com/drjekyllthemes/drjekyllthemes.github.io repo (and enable HTTPS on the go). There is no `gh-pages` branch for example. And deploying from `master` branch might be broken because there is no `Gemfile`.

The latter we can fix together when I open a PR to get the whole site updated again.

**Comment by geraldb** [comment]
i see - so this is a new website setup?

here's the proposal / idea - you create a new empty repo drjekyllthemes.github.io  and i first rename the "old" to website.old.  than you can work from "green field" and do whatever.  if that works for you?

**Comment by midzer** [comment]
Thanks for your proposals. I will think about it.

As current live site won't break when GitHub Pages can't build properly with those PRs, we should be safe to experiment with any changes we want in the repo.

**Comment by geraldb** [comment]
sorry if i am misunderstanding - is this a one time-operation? or do you have plans for more updates?   

let me rename back to drjekyllthemes.github.io  and than if you are interested you tell me about option 1) or 2) for the invite and than you can merge your changes (pull request).

**Comment by midzer** [comment]
Thanks for your trust in my person.

I would love to maintain Dr. Jekyll site as an owner and update it (manually for now) from time to time.

**Comment by geraldb** [comment]
you are more than welcome.  i send you the invite via github (per email - you should also see the invite on github.com here at the org)  to join the org  and you are welcome to do whatever e.g. rename  drjekyll.github.io to website.old (as i have done) and start on a "green field" from srcratch or to update the old "classic" website / repo. up-to-you. welcome.

**Comment by geraldb** [comment]
one more thing - not sure if needed - i transfer the <https://github.com/yorobot/planetjekyll> build script repo over here  and rename to /build

**Comment by midzer** [comment]
Yeah, would be nice to have all build scripts in one place/orga together.

Happy weekend and a good start in the week, @geraldb

**Comment by geraldb** [comment]
thanks for your updates and bring the website back to life (from the dead).   sorry for the delay about the /build repo transfer. i have no access to yorobot now.  i need the "on-site" computer (with stored password) to retry tomorrow (monday).

**Comment by geraldb** [comment]
@midzer   i transfered the /build repo see <https://github.com/drjekyllthemes/build>. i also spent a couple of hours to try to "modernize" / update the scripts but still a mess. not sure if you are using these scripts.

**Pull request merged**
