### PR TITLE
Add new theme - "Mr.Brown"

### PR DESCRIPTION
**Pull request by artemsheludko**

### CODE REVIEW

**Comment by geraldb** [comment]
@artemsheludko  Thanks for adding Mr. Brown. Great theme. Keep it up. Cheers.

**Comment by artemsheludko** [comment]
Thanks)

**Comment by artemsheludko** [comment]
Why I don't see theme on the site?

**Comment by geraldb** [comment]
@artemsheludko  You have to wait for the next site update - the themes.yml datafile gets linked in with a git module - see <https://github.com/drjekyllthemes/drjekyllthemes.github.io>. Cheers.

**Pull request merged**
