### PR TITLE
jsimple and jnegative

### PR DESCRIPTION
**Pull request by paulmostowyj**
added details of both to the yaml and included the thumbnails

### CODE REVIEW

**Comment by geraldb** [comment]
@paulmostowyj Thanks for adding jsimple and jnegative. Great themes. Keep it up. Cheers.

**Comment by paulmostowyj** [comment]
cheers

although i've checked the website and can't see the themes on there

**Comment by geraldb** [comment]
@paulmostowyj  See the F.A.Q entry: A: Thanks for your patience. The themes.yml is only used by the drjekyll package manager with "direct" web access. For the Dr Jekyll's website (see source) the themes.yml has to run through build steps (see source) to get github stars 'n' history etc. and, sorry, for now this is still a manual task / procedure that will get done "by hand". For your theme to show up, thus, please wait for the next site update.

**Comment by paulmostowyj** [comment]
thanks for taking the time to answer and I'm sorry I didn't read the README properly :)

**Pull request merged**
